name: Martini Software
title: Martini Software
pygments: true
markdown: redcarpet
exclude:
  - README.markdown
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - .ruby-version
  - .ruby-gemset
  - .gitignore
timezone: America/Chicago

assets:
  compress:
    css:  sass
    js:   uglifier

links:
  - title: About
    url: /about
  - title: Github
    url: https://github.com/martinisoft
    external: true
  - title: Twitter
    url: https://twitter.com/martinisoft
    external: true
