name: Martini Software
pygments: true
markdown: redcarpet
exclude: [Rakefile, Gemfile, Gemfile.lock, .rvmrc, .ruby-version, .ruby-gemset]
timezone: America/Chicago

assets:
  compress:
    css:  sass
    js:   uglifier

links:
  - title: About
    url: /about
  - title: Github
    url: https://github.com/martinisoft
    external: true
  - title: Twitter
    url: https://twitter.com/martinisoft
    external: true
