name: Martini Software
title: Martini Software
pygments: true
markdown: redcarpet
exclude:
  - README.markdown
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - .ruby-version
  - .ruby-gemset
  - .gitignore
timezone: America/Chicago

assets:
  cache: true
  css_compressor: sass
  js_compressor: uglifier
  sources:
    - _assets/javascripts
    - _assets/fonts
    - _assets/stylesheets
    - _assets/images

links:
  - title: About
    url: /about
  - title: Github
    url: https://github.com/martinisoft
    external: true
  - title: Twitter
    url: https://twitter.com/martinisoft
    external: true
  - title: Dribbble
    url: http://dribbble.com/martinisoft
    external: true
